@startebnf
!theme blueprint
SkinParam BackgroundColor #222
Repository = "Scal", ".", Capability (* Gerund verb form *),
    [
        ".",
        (
            Subjects (* Plural noun *) |
            Scope (* E.g. Meteorology *) |
            Technology
        ),
        {
            ".",
            ( Specialization | Technology | Variation )
        }
    ];
@end